# Generated by Django 2.2.6 on 2019-10-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(max_length=16)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
