# Generated by Django 2.2.6 on 2019-10-09 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('price', models.FloatField()),
                ('url', models.URLField(default='')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
