# Generated by Django 2.2.6 on 2019-10-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmall',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=10)),
                ('good_url', models.URLField()),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
                ('describe', models.TextField()),
                ('shop', models.CharField(max_length=50)),
                ('shop_url', models.URLField()),
            ],
        ),
    ]
