# Generated by Django 2.2.6 on 2019-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tmall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmall',
            name='describe',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tmall',
            name='price',
            field=models.FloatField(max_length=10),
        ),
    ]
