# Generated by Django 2.2.6 on 2019-10-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191010_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmall',
            old_name='price',
            new_name='goods_price',
        ),
    ]
