# Generated by Django 2.2.6 on 2019-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191010_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmall',
            name='goods_price',
            field=models.CharField(max_length=10),
        ),
    ]
