# Generated by Django 2.2.6 on 2019-10-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191010_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tmall',
            old_name='good_url',
            new_name='goods_url',
        ),
    ]
