# Generated by Django 2.2.6 on 2019-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20191010_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='You',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('goods', models.CharField(max_length=200)),
                ('goods_url', models.URLField()),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
                ('describe', models.CharField(max_length=200)),
            ],
        ),
    ]
