# Generated by Django 2.2.6 on 2019-10-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('keyword', models.CharField(max_length=20)),
                ('goods', models.CharField(max_length=200)),
                ('goods_url', models.URLField()),
                ('image_url', models.URLField()),
                ('price', models.FloatField()),
                ('shop', models.CharField(max_length=50)),
                ('shop_url', models.URLField()),
            ],
        ),
    ]
