# Generated by Django 2.2.6 on 2019-10-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_jd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jd',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='jd',
            name='shop_url',
        ),
    ]
