# Generated by Django 2.2.6 on 2019-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20191021_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='jd',
            name='shop',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='jd',
            name='shop_url',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jd',
            name='goods',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jd',
            name='goods_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jd',
            name='image_url',
            field=models.TextField(),
        ),
    ]
